### ISSUE TITLE
retain backwards compatibility

### ISSUE THREAD

**Issue by konikvranik** [konikvranik/home-assistant#16]
**Component/platform:**
hdmi_cec

**Description of problem:**
Retain backwards compatibility of configuration.
"devices" in configuration schema let in original form or new functionality.

Update devices schema to accept original or new configuration.

**Expected:**
Both configuration formats works

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
One of 
```yaml
hdmi_cec:
  devices:
    1: Pi Zero
    2:
      1: Fire TV Stick
      2: Chromecast
      3: Another Device
    3: BlueRay player
```
or
```yaml
hdmi_cec:
  devices:
    TV: 0.0.0.0
    Pi Zero: 1.0.0.0
    Fire TV Stick: 2.1.0.0
    Chromecast: 2.2.0.0
    Another Device: 2.3.0.0
    BlueRay player: 3.0.0.0
```
